### ISSUE TITLE
Need a demo site

### ISSUE THREAD

**Issue by praveenpuglia** [praveenpuglia/vuetify-daterange-picker#10]
Yeah! Let people play

**Comment by praveenpuglia** [comment]
@vinaypuppal wanna shoot at it?

**Comment by praveenpuglia** [comment]
Now available at http://vuetify-daterange.surge.sh/

**Comment by vinaypuppal** [comment]
Sorry I did not notice this issue.

> @vinaypuppal wanna shoot at it?

I mentioned how to deploy `demo` folder in this PR's description #3 

---
It would be better if you can add codesandbox demo also to readme like this 
[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/54yno7n89p)

**Comment by praveenpuglia** [comment]
Go ahead and add this in Readme and send me a PR :)
