### ISSUE TITLE
does not work with vuetify 1

### ISSUE THREAD

**Issue by ragas49** [praveenpuglia/vuetify-daterange-picker#14]
can you please update this to work with vuetify 1. vuetify 1 expects allowed dates in date picker to be function, this is passing a object at the moment

**Comment by praveenpuglia** [comment]
Hi!
Thanks for reporting it. 
I hear you. In the process of updating it. Will be working on this over the weekend. 👍

**Comment by praveenpuglia** [comment]
@ragas49 Fixed it. Pushing to npm as I speak! :)
