### ISSUE TITLE
[Feature request] Daterange picker in pop up menu 

### ISSUE THREAD

**Issue by hannonq** [praveenpuglia/vuetify-daterange-picker#17]
Hi, first of all, nice component!

I was wondering if there is a way to use it as a pop up menu, [like the official date picker from Vuetify](https://vuetifyjs.com/en/components/date-pickers#example-date-dialog-and-menu).

Ideally, the menu will only show up when the user clicks on the input field to change the date.

Thanks!

**Comment by praveenpuglia** [comment]
The examples I have are using menus. Can you please tell me exactly which demo you are talking about so I can understand the request better?

**Comment by hannonq** [comment]
Thanks for the quick reply.

I was referring to [this example](https://codepen.io/anon/pen/erjxod?&editors=101), but the code snippet you posted above does the trick very easily.

I'm a complete newbie in Vuejs (and fairly new to Javascript), so I didn't manage to put that together myself.

Since I'm happy with the proposed solution, I'll close this issue for now. And I would suggest that you put this nice example also in the usage guide, since this is a very common need :)

**Comment by praveenpuglia** [comment]
@hannonq the latest demo now includes the menu example at the bottom. :)

**Comment by hannonq** [comment]
Awesome :)
Thanks @praveenpuglia !
