### ISSUE TITLE
How to change start and end date labels?

### ISSUE THREAD

**Issue by chanlito** [praveenpuglia/vuetify-daterange-picker#19]
`Title says it all.`

**Comment by praveenpuglia** [comment]
Hey @chanlito , currently there's no way it can be done but I can definitely add a prop for that.
Or, even better, if you wanna fix this and send a PR, that would be so awesome :)

**Comment by pwnz22** [comment]
How about to removing the formatting string? (MM-DD-YYYY)

**Comment by praveenpuglia** [comment]
That option isn't there right now. Happy to have a PR that does that. Should be a simple boolean prop passed as `show-format`or something similar
