### ISSUE TITLE
do you have maxDate .. can I set maxDate?

### ISSUE THREAD

**Issue by amrbedair** [praveenpuglia/vuetify-daterange-picker#23]
Can I allow selecting ranges in the future?

**Comment by praveenpuglia** [comment]
I don't have that as of yet. I am working on a rewrite of the API though and allowing more options. Will be fixed soon!

**Comment by praveenpuglia** [comment]
Hi! @amrbedair. The options object now accepts a maxDate and if not provided, it defaults to today. Hope this solves your problem :)

**Comment by amrbedair** [comment]
@praveenpuglia thank you .. I will try it
