### ISSUE TITLE
Allow to pick dates on one month only

### ISSUE THREAD

**Issue by pwnz22** [praveenpuglia/vuetify-daterange-picker#25]
Hello guys!

Please help to set options for my needs.

I want to allow to user to pick dates in range of one month of any year. Thanks.

**Comment by praveenpuglia** [comment]
You can already do that using the `minDate` and `maxDate` options. Did you try using those values?

**Comment by pwnz22** [comment]
Yes, i tried, but didnt get what i need. I dont know which values to set to allow user to pick any dates between any month of one year. For example i can pick: 01.05.2018 - 20.05.2018 but not 01.05.2018 - 20.06.2018.

Can you explain how to use that options.

**Comment by praveenpuglia** [comment]
How about setting `minDate: '2018-05-01'` & `maxDate: '2018-05-20'` ?

**Comment by pwnz22** [comment]
Look user can choose any day from one month and any year.  I have restriction of picking between one month. 
Examples of user can pick:

2017-05-01 - 2017-05-30
2018-01-20 - 2018-01-25
But not:

2017-05-01 - 2017-06-05
2018-02-20 - 2018-03-25

etc...

**Comment by praveenpuglia** [comment]
oh! okay. Now I got it. So you want to allow the _duration_ to be max a month doesn't matter which month it is. 

Currently, there's no way to do this. I'll have to think about the API a little and get back to you with a solution soon.

**Comment by mariokresic** [comment]
You can use computed props to change maxDate prop. 

etc.

minDate = firstPickedDate;
maxDate = minDate + 30days

**Comment by praveenpuglia** [comment]
I have looked into this but it seems like @mariokresic 's way is the most convenient way of doing this right now. Anything else I tried required change to the actual datepicker element.
