### ISSUE TITLE
[Feature Request] Select textfield style

### ISSUE THREAD

**Issue by jasonrhaddix** [praveenpuglia/vuetify-daterange-picker#27]
Feature request: Ability to select the type of textfield through props or options (i.e. Regular, Box, Solo or Outline)

Edit: Would also include updating to latest Vuetify 1.2.x

I'm willing to submit a PR.

**Comment by praveenpuglia** [comment]
A PR is absolutely welcome! :)

**Comment by jasonrhaddix** [comment]
@praveenpuglia forgive me, but I have not had a chance to work on this. Feel free to close this if no one else is will to do a PR.

**Comment by praveenpuglia** [comment]
Hi!

I built a new version from ground up keeping simplicity of use in mind. Can you please try it out and let me know if that works for you?

P.S - I still need to add the option to pass in presets. 

https://vuetify-daterange-picker.gitbook.io/docs/

**Comment by praveenpuglia** [comment]
This has been fixed in latest version 3. You can now pass `input-options` prop to the picker and to that you can any prop that vuetify's `v-input` accepts. So you can not only change the input style but also other aspects of the component.
