### ISSUE TITLE
Input triggers twice

### ISSUE THREAD

**Issue by outoppie** [praveenpuglia/vuetify-daterange-picker#29]
It appears that every date selection triggers the input event twice.  You can see this in the sandbox by adding console.log

**Comment by praveenpuglia** [comment]
Hi!
This is intended. Each time a date is selected, the combination of start and end date is sent out. What's expected?

**Comment by outoppie** [comment]
Hi Praveen

 

Many thanks for responding and thanks for creating the date range picker.

 

Yes, I receive start and end date in the range field.  Not sure if it is intended, but my query is that each time I select either start or end date, is it correct that the input event fires twice ?

 

Regards

Mike Moncrieff

Computer Leverage

**Comment by praveenpuglia** [comment]
Yes! that's how I designed it. I should probably also add an option to give `Apply` and `Cancel` buttons which will ensure the event gets fired only when `Apply` is clicked.

**Comment by outoppie** [comment]
Thanks once again for the quick response.  I have adjusted my code accordingly.
