### ISSUE TITLE
Allow empty fields and clear

### ISSUE THREAD

**Issue by neufman** [praveenpuglia/vuetify-daterange-picker#30]
Hello,

Is it possible to initialize daterange picker with empty fields ?
After select a range, a reset button would be great !

Thanks !

**Comment by praveenpuglia** [comment]
Hi!
In the `options` object, if you pass `startDate` and `endDate` as empty string. It should initialize the fields with empty values.

Let me know if this doesn't work for you.

**Comment by neufman** [comment]
It doesn't seem to work.
Inputs have value "Invalid Date".

**Comment by praveenpuglia** [comment]
I have fixed part 1 of the issue in 57b06f2e9d211582162c13d823eca941bfda94d2.
for part 2, I am going to create a new issue and update there.
