### ISSUE TITLE
vertical pickers

### ISSUE THREAD

**Issue by arawwad** [praveenpuglia/vuetify-daterange-picker#31]
![screenshot from 2018-10-18 16-21-39](https://user-images.githubusercontent.com/25812184/47161330-20dbe280-d2f2-11e8-8e82-46a7f6844916.png)
any idea why I have the picker vertical not horizontal ??

**Comment by praveenpuglia** [comment]
Did you import the CSS too?

**Comment by arawwad** [comment]
I forgot to. thanks for the response :+1:
