### ISSUE TITLE
[Feature Request] closeable calendar pane

### ISSUE THREAD

**Issue by alex-mos** [praveenpuglia/vuetify-daterange-picker#33]
I'd like to close calendar pane after choosing date range like at [element.io](https://element.eleme.io/#/en-US/component/date-picker#date-range)
Add this option please.

**Comment by praveenpuglia** [comment]
You mean autoclose right?

**Comment by alex-mos** [comment]
Yes. Autoclose after loosing focus.

**Comment by praveenpuglia** [comment]
Hi, have you looked at the "Open in Menu" example here - http://vuetify-daterange.surge.sh/ ?
The daterange picker itself doesn't do any sort of handling like that. You can put this component inside any other overlay-ish component to get the same effect. 

Will that do the job? let me know.

It still doesn't solve the "Select two dates to auto close" use case. If that's something you are looking for, let me know.

**Comment by praveenpuglia** [comment]
Hi!

I built a new version from ground up keeping simplicity of use in mind. Can you please try it out and let me know if that works for you?

P.S - I still need to add the option to pass in presets. 

https://vuetify-daterange-picker.gitbook.io/docs/

**Comment by alex-mos** [comment]
Hi Praveen!
I tested version 3 and it completely solves this issue.
Date-picker is closed by default and appears after a click on the input.
Thank You!

**Comment by praveenpuglia** [comment]
Closing this then! :)
