### ISSUE TITLE
Doesn't work with vue-cli 3 when use Build

### ISSUE THREAD

**Issue by skortabeast** [praveenpuglia/vuetify-daterange-picker#40]
When use Build with vue cli 3 , data picker not use own style, but with dev  all is ok 
build version looks like
![image](https://user-images.githubusercontent.com/10978770/50289051-9b92bc80-045f-11e9-9b45-cd97a8462b65.png)
but dev version looks 
![image](https://user-images.githubusercontent.com/10978770/50289076-a9484200-045f-11e9-9624-e0c7daba525e.png)

dev option - "serve": "vue-cli-service serve",
build -  "build": "rm -rf ../public/{js,css,img} && vue-cli-service build --no-clean --watch"

but if copy paste DateRange component to my project and specify in each component all is ok

**Comment by luizfschrickte** [comment]
Same here, can't solve the issue - tried importing the css using ~, @ but all result in the same problem. Any help would be appreciated - this doesn't look like a complicated issue.

**Comment by pzeugin** [comment]
I just encountered the exact same problem. Any help is greatly appreciated.

**Comment by praveenpuglia** [comment]
I'll try fixing this over the weekend. I am sorry, I have been pathetically occupied elsewhere and couldn't look into any of it.

**Comment by praveenpuglia** [comment]
Hi!

I built a new version from ground up keeping simplicity of use in mind. Can you please try it out and let me know if that works for you?

P.S - I still need to add the option to pass in presets. 

https://vuetify-daterange-picker.gitbook.io/docs/

**Comment by praveenpuglia** [comment]
This has been closed in latest version 3. Please try and let me know if that doesn't work for you.
