### ISSUE TITLE
Highlight range doesn't work with vuetify 1.4

### ISSUE THREAD

**Issue by jvbianchi** [praveenpuglia/vuetify-daterange-picker#41]
This library is not compatible with vuetify version 1.3 and up.

**Comment by pzeugin** [comment]
Highlight range is displayed as some weird dots with newest vuetify version. Does anybody now how to resolve this issue?

**Comment by praveenpuglia** [comment]
I have checked this. It's probably a class name issue. Will fix this

**Comment by praveenpuglia** [comment]
Hi!

I built a new version from ground up keeping simplicity of use in mind. Can you please try it out and let me know if that works for you?

P.S - I still need to add the option to pass in presets. 

https://vuetify-daterange-picker.gitbook.io/docs/

**Comment by praveenpuglia** [comment]
Closed this in latest version 3.
