### ISSUE TITLE
Internalization name of presets

### ISSUE THREAD

**Issue by magvan** [praveenpuglia/vuetify-daterange-picker#42]
I make internalization.
![image](https://user-images.githubusercontent.com/8927781/51374905-7011f900-1b15-11e9-8e1e-f2a4ead3e9f0.png)
labels translated success. dataRangeLabels
![image](https://user-images.githubusercontent.com/8927781/51375014-c2531a00-1b15-11e9-9022-0ea9f670c040.png)
But presets not translated.
![image](https://user-images.githubusercontent.com/8927781/51375094-f62e3f80-1b15-11e9-945d-92a249365b7e.png)
![image](https://user-images.githubusercontent.com/8927781/51375112-0d6d2d00-1b16-11e9-8042-db9f8b328302.png)

I tried to transfer as computed property, dont works.

Solution to the problem: property "presets" make as props.

**Comment by praveenpuglia** [comment]
Thanks for the codesandbox setup. I'll try this out and see if I can fix things :)

**Comment by praveenpuglia** [comment]
Making presets as a prop will break code for everyone else who is already using the component. That is why I am thinking of a diff way. I may as well do that but release it as a separate version.

**Comment by praveenpuglia** [comment]
Hi!

I built a new version from ground up keeping simplicity of use in mind. Can you please try it out and let me know if that works for you?

P.S - I still need to add the option to pass in presets. 

https://vuetify-daterange-picker.gitbook.io/docs/

**Comment by praveenpuglia** [comment]
Version 3.1.1 should fix this issue. Hence closing.
