### ISSUE TITLE
Does not work with Nuxt.js

### ISSUE THREAD

**Issue by eliyas5044** [praveenpuglia/vuetify-daterange-picker#43]
Hi, thanks for your awesome plugin :)
I used this with Vue.js and worked fine. But in my current project, it's not working.
> Environments: 
```
"nuxt": "^2.4.3",
"vuetify": "^1.5.0",
"vuetify-daterange-picker": "^2.6.2"
```
[![Edit nuxt-vuetify](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/71r30w97y0)

appreciate your help :)

**Comment by praveenpuglia** [comment]
Hi!

I built a new version from ground up keeping simplicity of use in mind. Can you please try it out and let me know if that works for you?

P.S - I still need to add the option to pass in presets. 

https://vuetify-daterange-picker.gitbook.io/docs/

**Comment by praveenpuglia** [comment]
Also, in your codesandbox demo, I see this. Is that intended?
<img width="538" alt="image" src="https://user-images.githubusercontent.com/313363/52894091-3a226c00-31ca-11e9-80ae-aad9c778cc47.png">

**Comment by alvinthen** [comment]
FYI, I need to disable ssr in my nuxt-config.js in order to use this.

```js
plugins: [
  { src: '~/plugins/datepicker.js', ssr: false }
],
```

**Comment by praveenpuglia** [comment]
Hi!

Can you please try the latest version of the component 3.1.1 and see if that works?
Note - the new version has breaking changes.

**Comment by eliyas5044** [comment]
@praveenpuglia sorry, I was on vacation. I will try the new version and let you know. Thanks for your attention.
