### ISSUE TITLE
[v3] end date picker doesn't conform to min prop

### ISSUE THREAD

**Issue by alvinthen** [praveenpuglia/vuetify-daterange-picker#44]
On v3.0.1, `min` doesn't seem to affect the end date picker.

<img width="680" alt="screenshot 2019-02-28 at 10 47 13" src="https://user-images.githubusercontent.com/771989/53538037-0b4fb280-3b47-11e9-9c23-7413ccb8e377.png">

```vue
<v-date-range
  v-model="range"
  :min="'2019-02-28'"
/>
```

**Comment by praveenpuglia** [comment]
Will fix this on March 02.
You can also send me a PR, that would be so awesome! :)

**Comment by praveenpuglia** [comment]
Thanks for the issue. It's fixed now in the latest version.
