### ISSUE TITLE
How to change 'apply', 'close' buttons and menu activator?

### ISSUE THREAD

**Issue by pawel-miczka** [praveenpuglia/vuetify-daterange-picker#46]
I want to change buttons from menu under pickers. How can I do it?
Also I want to change activator. Is it possible?

**Comment by praveenpuglia** [comment]
Not right now. no. I am having hard time maintaining this project. I would really love someone else to join in. :(

**Comment by pawel-miczka** [comment]
Ok :( .. I'm closing this issue then.
Maybe as i find time I will join, make some changes and open PRs but not so soon.
