### ISSUE TITLE
How to reset daterange value?

### ISSUE THREAD

**Issue by sergiofactvs** [praveenpuglia/vuetify-daterange-picker#48]
Hi, it is possible to reset the daterange input value?

**Comment by praveenpuglia** [comment]
Hi!

This option doesn't yet exist. I was wondering how to do this. Would you like it as a method you can call on the ref to the component?

So you could do something like 
```html
<v-daterange ref="daterange"></v-daterange>
```
and then in JS
```js
// somewhere in your code
this.$refs.daterange.reset();
```

This could very well be extended in the UI as well by giving a reset button.

**Comment by mr-africa** [comment]
@sergiofactvs 
You can use `clearable` option of `text-field` also.

```vue
        <v-daterange
            v-model="dateRange"
            :input-props="{
                clearable: true
            }"
        />
```

**Comment by mr-africa** [comment]
But `clearable` option in `input-props` just clear input and don't clear daterange value.
@praveenpuglia could you add real clearable option to the component please

**Comment by praveenpuglia** [comment]
I'll work on it this week.

**Comment by praveenpuglia** [comment]
Hi!
There's now a way to reset the picker. 
Please check this out - https://vuetify-daterange-picker.gitbook.io/docs/api#show-reset

**Comment by hellowest** [comment]
Hi Guys,

I'm working the vuetify date range picker and the reset option , its still not available from what I'm seeing.
Some news on this subject ?
Thank you.
