### ISSUE TITLE
Migrate from moment.js to `date-fns`

### ISSUE THREAD

**Issue by vinaypuppal** [praveenpuglia/vuetify-daterange-picker#5]
Reason: moment.js produces larger bundle size and since we are not using all of moment.js it makes sense to import what we use only instead of full moment.js but moment.js has a performance overhead. Read this post for more info: https://raygun.com/blog/moment-js-vs-date-fns/

So it's better to use [date-fns](https://date-fns.org/) and import only what we use like
```
import format from 'date-fns/format';
```

**Comment by praveenpuglia** [comment]
Thanks for the suggestion. I was thinking of removing it too. Let me take a look.

**Comment by praveenpuglia** [comment]
Would you be interested in taking this up? All we need is a format function.

**Comment by vinaypuppal** [comment]
Yeah sure, so should we make `date-fns` as `peerDependency` or integrate into this component as you said we will be using only one format function so there won't be huge file size differences of our dist files. What do you say?

**Comment by praveenpuglia** [comment]
we'll need it as a dependency but just import those two functions. Webpack can take care of the rest.
