### ISSUE TITLE
Markup is broken

### ISSUE THREAD

**Issue by akaNightmare** [praveenpuglia/vuetify-daterange-picker#50]
![image](https://user-images.githubusercontent.com/4151616/55344791-f30ce380-54b6-11e9-96e9-8912c5752121.png)

**Comment by praveenpuglia** [comment]
Explanation? What do you mean?

It looks like broken because by default the input takes up a specific width which cuts off the text.

Try this.

```html
<v-daterange :input-props="inputProps"></v-daterange>
```

```js
data() {
  return {
    inputProps: {style: { width: '240px' } },
  }
}
```
