### ISSUE TITLE
Lack of documentation based on promoted examples

### ISSUE THREAD

**Issue by timothymarois** [praveenpuglia/vuetify-daterange-picker#53]
Based on examples, this plugin lacks documentation to replicate examples provided here. 

http://vuetify-daterange.surge.sh/

**Comment by timothymarois** [comment]
I found this after some google searches and it provides the actual example code 
https://codesandbox.io/s/q9vzox5y6j

**Comment by praveenpuglia** [comment]
Hi!
I know it lacks proper documentation and it sucks! But two reasons.
1. I am just way too much occupied in day job. Startup Life!
2. Codesandbox doesn't work with glob in stylus files. So I am unable to create a vuetify demo there. If you know of a workaround, let me know and I'll be happy to add multiple demos there.
