### ISSUE TITLE
Dialog action button text config (Localisation support)

### ISSUE THREAD

**Issue by iolinpic** [praveenpuglia/vuetify-daterange-picker#60]
currently we could change calendar language via props, but dialog actions seams to be hardcoded as "Cancel", "Apply"
` <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn flat @click="reset">Reset</v-btn>
          <v-btn flat @click="menu = false">Cancel</v-btn>
          <v-btn @click="applyRange" color="primary" :disabled="!bothSelected"
            >Apply</v-btn
          >
</v-card-actions>`

**Comment by IgnasJan** [comment]
In addition, the first day of the week should be changed according to the locale.

**Comment by praveenpuglia** [comment]
Fixed in 3.2. Released to NPM. Thanks for reporting!
