### ISSUE TITLE
Change value prop

### ISSUE THREAD

**Issue by Kshopper93** [praveenpuglia/vuetify-daterange-picker#62]
Hello,

i want to set a default start and end date in my picker but its didnt work. Here my code:

```html
<v-daterange
 v-model="range"
 display-format="DD-MM-YYYY"
:input-props="inputProps"
:menu-props="menuProps"
 :value="datepickerinivalues"
></v-daterange>

```

Here my data:

```js
inputProps: { solo: true, style: { width: '500px' } },
menuProps: { offsetY: true, closeOnContentClick: false },  
datepickerinivalues:{ start: "2019-05-20", end: "2019.05.24"}
```

**Comment by praveenpuglia** [comment]
Your use of `v-model` and `:value` is conflicting.
v-model itself uses `value` prop internally.

tl;dr
if you need default values, set your `range` data property to those default values and then pass that `range` to `v-model`

Basically,

- remove `:value`
- change the name of `datepickerinivalues` to `range`
