### ISSUE TITLE
Date format issue

### ISSUE THREAD

**Issue by Zigotote** [praveenpuglia/vuetify-daterange-picker#70]
Hello, 
I tried to use the date range picker but when I do so I have this error :
![image](https://user-images.githubusercontent.com/34279302/69233755-cb75a300-0b8d-11ea-901a-f3885bc68210.png)

It's because date formatting isn't correct on the code : it should be "yyyy-MM-dd" instead of "YYYY-MM-DD" (see [date-fns doc](https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md)).
I would have done the changes by myself but I can't manage to install all the dependencies required for the project.

Could you please fix it ? Your tool seems so great, I'd love to be able to use it on my project !

**Comment by praveenpuglia** [comment]
I think it's because date-fns changed their parsing logic and what letters denote what to be compliant with standards and how other libraries like moment does it.

Can you please tell me from your package-lock.json or yarn.lock file which exact version of date-fns you are using?

**Comment by Zigotote** [comment]
You're right, I'm not using the same version as you : my date-fns version is 2.7.0.

**Comment by ashishnimrot** [comment]
Same problem, How to solved/handle this exception.

**Comment by Zigotote** [comment]
The first solution is to downgrade your date-fns version, to ues 1.30.1 as @praveenpuglia does.

The second one is to use another plugin, such as [https://github.com/charliekassel/vuejs-datepicker](vuejs-datepicker).

Or, if you have time, maybe you can modify this project to use a higher version of date-fns. The idea is just to replace all the "MM-DD-YYYY" by "MM-dd-yyyy" (or whatever format you want to use).

**Comment by praveenpuglia** [comment]
I am desperately looking for a maintainer. Everyone wants to use it but nobody wants to maintain and I don't have enough time to maintain it further. It's hard to keep up to date with vuetify changes and more so after things radically changed in v2. 

Anyone willing to chip in?

**Comment by praveenpuglia** [comment]
If this is important for you all, I'll try to see if I can do something in a week or so. But no guarantees.

**Comment by Zigotote** [comment]
I made a pull request  #71 to solve this problem.
However, I didn't tested it (I have never developed a Vuejs plugin before and I don't know how to test it). It should work but it will maybe require minor changes.

**Comment by praveenpuglia** [comment]
closed in #71
