### ISSUE TITLE
Cannot find module "vuetify/lib"

### ISSUE THREAD

**Issue by Zigotote** [praveenpuglia/vuetify-daterange-picker#72]
Hello,
I tried to use the new version of the plugin but know I have this error when I run my application 
![image](https://user-images.githubusercontent.com/34279302/70540288-3e5ab400-1b65-11ea-92ae-adeff1a0583d.png)

Do you know why I have this message ?

**Comment by praveenpuglia** [comment]
Which version of vuetify are you trying to install or have installed?

**Comment by Zigotote** [comment]
I'd like to use the last one : 3.2.0.
This are my dependencies, in my package.json : 
![image](https://user-images.githubusercontent.com/34279302/70608365-47e52a00-1c00-11ea-8fa4-cbe5e67ad9e4.png)

**Comment by praveenpuglia** [comment]
I don't see vuetify itself in the dependencies. Have you installed vuetify? My component doesn't work if you don't have vuetify.

**Comment by Zigotote** [comment]
Thanks for your fast reply !! I didn't see in your documentation that I should install vuetify, but I will add it, thanks !

**Comment by praveenpuglia** [comment]
No Problemo! Everything should work fine once you are done installing vuetify. Don't install versino 2 though. This guy only works with 1.X
