### ISSUE TITLE
No typescript support

### ISSUE THREAD

**Issue by andreixk** [praveenpuglia/vuetify-daterange-picker#79]
Tying to use the package in a typescript project:

```
Could not find a declaration file for module 'vuetify-daterange-picker'
```

**Comment by praveenpuglia** [comment]
Hey!

So, I no longer maintain the project but if it still works for you you can do the following workaround to get past through TS.

If you have scaffolded your project using vue-cli, you should have a shims-vue.d.ts file where you can add the following line

```ts
declare module 'vuetify-daterange-picker';
```

This should make TS warning go away.
