### ISSUE TITLE
DateRange component doesn't trigger any HMR while developing

### ISSUE THREAD

**Issue by praveenpuglia** [praveenpuglia/vuetify-daterange-picker#8]
@vinaypuppal In App.vue, we should really be pointing the source DateRange.vue and not the dist version. 
https://github.com/praveenpuglia/vuetify-daterange-picker/blob/master/demo/App.vue#L20-L21
This will stop HMR from working for any source changes in DateRange.vue.

```
import DateRange from '../src/DateRange';
```
should be good enough for development.

**Comment by praveenpuglia** [comment]
I am gonna be fixing this with the next PR.

**Comment by vinaypuppal** [comment]
But I thought `demo` folder contains example on how to use this component. No problem change it to `src` file if it helps for development, we can add a code sandbox link to Readme.

**Comment by praveenpuglia** [comment]
Actually you are right. So what I am doing is keeping App.vue as is but adding the build step in dev server in watch mode. That should do the trick.

This to be precise.
```sh
npm run build -- -w poi demo/index.js
```
